# Generated by Django 3.2 on 2022-01-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_lecture_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='students',
            field=models.ManyToManyField(to='student_lecture_app.Student'),
        ),
    ]
